version: "2.4"
services:
    mongo:
        image: mongo:3.6
        ports:
            - "27017:27017"
        tmpfs:
            - /data/db

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node
        tmpfs:
            - /usr/share/elasticsearch/data
