language: python

python: 3.6

dist: bionic

services:
    - docker

cache: pip

before_install:
    - |
      if [ "$SERVER" == "true" ]; then
        cd src/server
        pip install -r dev-requirements.txt
        pip install -e .
        cd ../..
      fi
    - |
      if [ "$SERVICES" == "true" ]; then
        docker-compose -f .travis-docker-compose.yml up -d
        cd src/server
        pip install -r requirements.txt
        cd ../..
        bash scripts/wait-elastic-online.sh
      fi
    - |
      if [ "$CLIENT" == "true" ]; then
        cd src/clients/python
        pip install -r dev-requirements.txt
        pip install -e .
        cd ../../../
      fi
    - |
      if [ "$START_SAMS" == "true" ]; then
        cd src/server
        (nohup honcho start &)
        cd ../../
      fi
    - |
      if [ "$BEHAVE" == "true" ]; then
        pip install -r tests/features/requirements.txt
      fi

jobs:
    include:
      - name: "lint"
        script: cd src/server && flake8 && cd ../clients/python && flake8 && cd ../../../tests/server && flake8 && cd ../clients/python && flake8
        env:
          - SERVER=true
          - CLIENT=true
      - name: "server-unit"
        script: pytest tests/server --disable-pytest-warnings
        env:
          - SERVER=true
          - SERVICES=true
      - name: "clients-unit"
        script: pytest tests/clients --disable-pytest-warnings
        env:
          - SERVER=true
          - CLIENT=true
          - SERVICES=true
          - START_SAMS=true
      - name: "behave"
        script: behave tests/features --format progress2
        env:
          - SERVER=true
          - CLIENT=true
          - SERVICES=true
          - BEHAVE=true
